status:
  - Test
  - Prod

team:
  name: text

address:
  line1: text
  line2: text
  zip: text
  city: text
  country: text

post:
  +?title: text
  ?content: text
  chapo:
    type: text
    constraints:
        unique:
        check: char_length(chapo) < 200

member:
  firstname: text
  lastname: text
  nickname: text
  ?team_id:
  address_id:
  status: status | 'Test'
  __unique: [ firstname, lastname ]

tag:
    +name: text
    __check: name <> 'prolapse'

post_tag:
    post_id:
    tag_id:
    __pk: [ tag_id, post_id ]

